/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Invoice = IDL.Record({
  'breakfastCharge' : IDL.Float64,
  'checkIn' : IDL.Text,
  'discountValue' : IDL.Float64,
  'taxableAmount' : IDL.Float64,
  'breakfastAmount' : IDL.Float64,
  'isHourly' : IDL.Bool,
  'hours' : IDL.Float64,
  'cgst' : IDL.Float64,
  'discountAmount' : IDL.Float64,
  'createdAt' : IDL.Int,
  'discountType' : IDL.Text,
  'sgst' : IDL.Float64,
  'hourlyRate' : IDL.Float64,
  'guestAddress' : IDL.Text,
  'guestName' : IDL.Text,
  'roomNumber' : IDL.Text,
  'grandTotal' : IDL.Float64,
  'invoiceDate' : IDL.Text,
  'tariffPerNight' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'includeBreakfast' : IDL.Bool,
  'notes' : IDL.Text,
  'roomAmount' : IDL.Float64,
  'checkOut' : IDL.Text,
  'nights' : IDL.Nat,
  'roomCategory' : IDL.Text,
  'guestGST' : IDL.Text,
});

export const idlService = IDL.Service({
  'createInvoice' : IDL.Func([Invoice], [IDL.Text], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [], []),
  'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
  'getInvoicesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getNextInvoiceNumber' : IDL.Func([], [IDL.Text], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'updateInvoice' : IDL.Func([IDL.Text, Invoice], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Invoice = IDL.Record({
    'breakfastCharge' : IDL.Float64,
    'checkIn' : IDL.Text,
    'discountValue' : IDL.Float64,
    'taxableAmount' : IDL.Float64,
    'breakfastAmount' : IDL.Float64,
    'isHourly' : IDL.Bool,
    'hours' : IDL.Float64,
    'cgst' : IDL.Float64,
    'discountAmount' : IDL.Float64,
    'createdAt' : IDL.Int,
    'discountType' : IDL.Text,
    'sgst' : IDL.Float64,
    'hourlyRate' : IDL.Float64,
    'guestAddress' : IDL.Text,
    'guestName' : IDL.Text,
    'roomNumber' : IDL.Text,
    'grandTotal' : IDL.Float64,
    'invoiceDate' : IDL.Text,
    'tariffPerNight' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'includeBreakfast' : IDL.Bool,
    'notes' : IDL.Text,
    'roomAmount' : IDL.Float64,
    'checkOut' : IDL.Text,
    'nights' : IDL.Nat,
    'roomCategory' : IDL.Text,
    'guestGST' : IDL.Text,
  });
  
  return IDL.Service({
    'createInvoice' : IDL.Func([Invoice], [IDL.Text], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [], []),
    'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
    'getInvoicesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getNextInvoiceNumber' : IDL.Func([], [IDL.Text], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'updateInvoice' : IDL.Func([IDL.Text, Invoice], [], []),
  });
};

export const init = ({ IDL }) => { return []; };