/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Invoice {
  'breakfastCharge' : number,
  'checkIn' : string,
  'discountValue' : number,
  'taxableAmount' : number,
  'breakfastAmount' : number,
  'isHourly' : boolean,
  'hours' : number,
  'cgst' : number,
  'discountAmount' : number,
  'createdAt' : bigint,
  'discountType' : string,
  'sgst' : number,
  'hourlyRate' : number,
  'guestAddress' : string,
  'guestName' : string,
  'roomNumber' : string,
  'grandTotal' : number,
  'invoiceDate' : string,
  'tariffPerNight' : number,
  'invoiceNumber' : string,
  'includeBreakfast' : boolean,
  'notes' : string,
  'roomAmount' : number,
  'checkOut' : string,
  'nights' : bigint,
  'roomCategory' : string,
  'guestGST' : string,
}
export interface _SERVICE {
  'createInvoice' : ActorMethod<[Invoice], string>,
  'deleteInvoice' : ActorMethod<[string], undefined>,
  'getInvoice' : ActorMethod<[string], Invoice>,
  'getInvoicesByDateRange' : ActorMethod<[string, string], Array<Invoice>>,
  'getNextInvoiceNumber' : ActorMethod<[], string>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'updateInvoice' : ActorMethod<[string, Invoice], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];